name: Build and Commit LaTeX CV

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-extra latexmk

      - name: Compile CV
        run: |
          mkdir -p build
          latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -output-directory=build src/content.tex
          mv build/content.pdf BALASCHSOLA.pdf  # Move PDF to root

      - name: Commit PDF to Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add BALASCHSOLA.pdf
          git commit -m "🚀 Auto-update BALASCHSOLA.pdf"
          git push